config/routes.rb
Rails.application.routes.draw do
    # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html 
  root 'homes#index'
  devise_for :users

  resources :cleanups   
  resources :states do
      resources :cities
  end
  
  resources :users, :only => :show
  resources :details, :only => :index

  namespace :admin do 
    resources :users, only: [:index, :destroy]
    resources :cleanups, only: [:index, :destroy]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cleanup.rb
class Cleanup < ApplicationRecord
    validates :title, presence: true
    validates :posted_by, presence: true
    validates :date, presence: true
    validates :state, presence: true
    validates :city, presence: true
    validates :cleanup_type, presence: true
    validates :volunteers, presence: true
    validates :total_trash, presence: true
    belongs_to :user

    mount_uploader :cleanup_photo, CleanupPhotoUploader


    CLEANUP_TYPES = [
        ["coastal", "Coastal"],
        ["roadside", "Roadside"],
        ["water", "Water"],
        ["other", "Other"]
    ]

    STATES = [
        ['Alabama', 'AL'],
        ['Alaska', 'AK'],
        ['Arizona', 'AZ'],
        ['Arkansas', 'AR'],
        ['California', 'CA'],
        ['Colorado', 'CO'],
        ['Connecticut', 'CT'],
        ['Delaware', 'DE'],
        ['District of Columbia', 'DC'],
        ['Florida', 'FL'],
        ['Georgia', 'GA'],
        ['Hawaii', 'HI'],
        ['Idaho', 'ID'],
        ['Illinois', 'IL'],
        ['Indiana', 'IN'],
        ['Iowa', 'IA'],
        ['Kansas', 'KS'],
        ['Kentucky', 'KY'],
        ['Louisiana', 'LA'],
        ['Maine', 'ME'],
        ['Maryland', 'MD'],
        ['Massachusetts', 'MA'],
        ['Michigan', 'MI'],
        ['Minnesota', 'MN'],
        ['Mississippi', 'MS'],
        ['Missouri', 'MO'],
        ['Montana', 'MT'],
        ['Nebraska', 'NE'],
        ['Nevada', 'NV'],
        ['New Hampshire', 'NH'],
        ['New Jersey', 'NJ'],
        ['New Mexico', 'NM'],
        ['New York', 'NY'],
        ['North Carolina', 'NC'],
        ['North Dakota', 'ND'],
        ['Ohio', 'OH'],
        ['Oklahoma', 'OK'],
        ['Oregon', 'OR'],
        ['Pennsylvania', 'PA'],
        ['Puerto Rico', 'PR'],
        ['Rhode Island', 'RI'],
        ['South Carolina', 'SC'],
        ['South Dakota', 'SD'],
        ['Tennessee', 'TN'],
        ['Texas', 'TX'],
        ['Utah', 'UT'],
        ['Vermont', 'VT'],
        ['Virginia', 'VA'],
        ['Washington', 'WA'],
        ['West Virginia', 'WV'],
        ['Wisconsin', 'WI'],
        ['Wyoming', 'WY']
    ]
    
end 

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  validates :role, inclusion: { in: ['user', 'admin'] }       
  has_many :cleanups, dependent: :destroy 

  def is_admin?
    role == 'admin'
  end

end

app/controllers/admin/cleanups_controller.rb
class Admin::CleanupsController < ApplicationController
    before_action :ensure_admin_user!
    
    def index
        @cleanups = Cleanup.all.order(:posted_by)
    end

    def destroy
        @cleanup = Cleanup.find(params[:id])
        @cleanup.destroy
        redirect_to admin_cleanups_path, notice: 'Cleanup deleted'
    end

    private

    def ensure_admin_user!
        unless current_user and current_user.is_admin?
            flash[:alert] = "Access denied."
            redirect_to root_path
        end
    end 
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
    before_action :ensure_admin_user!
    
    def index
        @users = User.all  
    end

    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to admin_users_path, notice: 'User deleted'
    end

    private

    def ensure_admin_user!
        unless current_user and current_user.is_admin?
            flash[:alert] = "Access denied."
            redirect_to root_path
        end
    end 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cities_controller.rb
class CitiesController < ApplicationController

    # GET /states/:state_id/cities/:id
    def show
        @cleanups = Cleanup.where(city: params[:id]).sort_by { |date| date }
        @city_name = params[:id]
    end
end

app/controllers/cleanups_controller.rb
class CleanupsController < ApplicationController

    # GET /cleanups
    def index
        @cleanups = Cleanup.all 
        @state_collection = Cleanup::STATES 
    end

    # GET /cleanups/:id
    def show
        @cleanup = Cleanup.find(params[:id])   
    end 

    # GET /cleanups/new
    def new
        @cleanup = Cleanup.new
        @state_collection = Cleanup::STATES
        @cleanup_type_collection = Cleanup::CLEANUP_TYPES 
    end

    # POST /cleanups
    def create
        @cleanup = Cleanup.new(cleanup_params)
        @cleanup.user = current_user
        if @cleanup.save
            flash[:notice] = 'You logged a cleanup!'
            redirect_to @cleanup
        else 
            flash[:alert] = @cleanup.errors.full_messages.join(', ')
            @state_collection = Cleanup::STATES
            @cleanup_type_collection = Cleanup::CLEANUP_TYPES 
            render action: 'new'
        end
    end

    # EDIT /cleanups/:id/edit
    def edit
        @cleanup = Cleanup.find(params[:id])
        @state_collection = Cleanup::STATES
        @cleanup_type_collection = Cleanup::CLEANUP_TYPES
    end

    def update
        @cleanup = Cleanup.find(params[:id])
        @cleanup.update(cleanup_params)
        if @cleanup.save
            flash[:notice] = 'Changes Saved'
            redirect_to cleanup_path
        else
            flash[:alert] = @cleanup.errors.full_messages.join(', ')
            @state_collection = Cleanup::STATES
            @cleanup_type_collection = Cleanup::CLEANUP_TYPES 
            render :edit 
        end
    end

    # DELETE /cleanups/:id
    def destroy
        @cleanup = Cleanup.find(params[:id])
        if @cleanup.destroy
            flash[:notice] = "Cleanup Deleted"
            redirect_to user_path
        end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cleanup_params
        params.require(:cleanup).permit(
            :user_id, 
            :title,
            :date, 
            :posted_by, 
            :state, 
            :city, 
            :cleanup_type, 
            :volunteers,
            :total_trash, 
            :description,
            :cleanup_photo,
            :remove_cleanup_photo
        )
    end 
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController

    # GET /details
    def index
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/states_controller.rb
class StatesController < ApplicationController

    # GET /states/:id
    def show
    # Find all cleanups in the state
        @cleanups = Cleanup.where(state: params[:id])
    # Find all the cities w/ cleanups in the state
        @cleanup_cities = @cleanups.map(&:city).uniq.sort_by { |cleanup_cities| cleanup_cities}
        @state_name = params[:id]
        @state_trash = @cleanups.sum(:total_trash)       
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def index   
    end

    # GET /users/:id
    def show
        @cleanups = current_user.cleanups.order(date: :desc)
    end
end 

app/helpers/cleanups_helper.rb
module CleanupsHelper
end

app/views/admin/cleanups/index.html.erb
<h1>Admin: List of Cleanups</h1>
<h4>To see the list of members, click here: <%= link_to "Users", admin_users_path %></h4>

<table class= "hover">
  <thead>
    <tr>
      <th width="200">User</th>
      <th width="500">Cleanup Event</th>
      <th width="250">Action</th>    
    </tr>
  </thead>
  <tbody>
    <% @cleanups.each do |cleanup| %>
    <tr>
      <td><%= cleanup.posted_by %></td> 
      <td><%= link_to cleanup.title, cleanup %></td> 
      <td><%=
        link_to "Delete",
        admin_cleanup_path(cleanup),
        method: :delete
      %></td>
    </tr>   
    <% end %>
  </tbody>
</table>

app/views/admin/users/index.html.erb
<h1>Admin: List of Users</h1>
<h4>To see the list of cleanup events, click here: <%= link_to "Cleanups", admin_cleanups_path %></h4>

  <ol>
    <% @users.each do |user| %>
    <li>
        <%= user.email %> |
        <%=
            link_to "Delete",
            admin_user_path(user),
            method: :delete
        %>
    </li>
    <% end %>
  </ol>

app/views/cities/show.html.erb
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><%= link_to "Home", root_path %></li> 
    <li><%= link_to "View Cleanups", cleanups_path %></li>
    <li><%= link_to "State", state_path(params[:state_id]) %></li>
    <li><span class="show-for-sr">Current: </span>City</li>
  </ul>
</nav>

<h1><%= "Cleanups By City: #{@city_name}" %></h1>
<h3>Looking for a specific cleanup? Locate it here, organized by date.</h3>

<table class= "hover">
  <thead>
    <tr>
      <th width="200">Date</th>
      <th>Cleanup Event</th>   
    </tr>
  </thead>
  <tbody>
  <% @cleanups.each do |cleanup| %>
    <tr>
      <td><%= cleanup.date.strftime("%m-%d-%Y") %></td> 
      <td><%= link_to cleanup.title, cleanup %></td>
    </tr>   
    <% end %>
  </tbody>
</table>

app/views/cleanups/_cleanup_form.html.erb
<h3>Please use the form below to log your cleanup. Fields marked with * are required.</h3>

<%= form_for @cleanup, :html => {:multipart => true} do |f| %>

<div class="field">
    <%= f.label :title, "Title*" %><br />
    <%= f.text_field :title %>
</div>
<div class="field">
    <%= f.label :posted_by, "Posted By*" %><br />
    <%= f.text_field :posted_by %>
</div>
<div class="field">
    <%= f.label :date, "Date*" %><br />
    <%= f.date_select :date %>
</div>
<div class="field">
    <%= f.label :state, "State*" %><br />
    <%= f.select(:state, @state_collection) %>
</div>
<div class="field">
    <%= f.label :city, "City*" %><br />
    <%= f.text_field :city %>
</div>
<div class="field">
    <%= f.label :cleanup_type, "Cleanup Type*" %><br />
    <%= collection_radio_buttons :cleanup, :cleanup_type, @cleanup_type_collection, :first, :last %>
</div>
<div class="field">
    <%= f.label :volunteers, "Number of Volunteers*" %><br />
    <%= f.number_field :volunteers %>
</div>
<div class="field">
    <%= f.label :total_trash, "Total Trash (lbs.)*" %><br />
    <%= f.number_field :total_trash %>
</div>
<div class="field">
    <%= f.label :description, "Description (optional)" %><br />
    <%= f.text_area :description %>
</div>
<div class="callout">
<div class="field">
    <p>Add a photo from your cleanup (optional):</p>
    <%= f.file_field :cleanup_photo %>
</div>
<div class="field">
    <% if f.object.cleanup_photo? %>
        <%= image_tag f.object.cleanup_photo.thumb.url %>
    <%= f.label :remove_cleanup_photo %> 
    <%= f.check_box :remove_cleanup_photo %>
    <% end %>
</div>
</div>

<div class="actions">
<div class="text-center">
    <%= f.submit "Log Cleanup", class: 'button sky' %>
    <%= link_to "Cancel", :back, class: 'button' %>    
</div>
</div>

<% end %>

app/views/cleanups/edit.html.erb
<div class="form-actions">
<h1>Edit Cleanup</h1>
  <p>
    Use this form to edit or delete your cleanup record. Please note: deleting a cleanup will permanently remove it from the site!
  </p>
</div>

<%= render 'cleanup_form', cleanup: @cleanup %>

<div class="actions">
<div class="text-center">
  <%= link_to "Delete Cleanup", @cleanup, :class => "button secondary", :method => :delete %>
</div>
</div>

app/views/cleanups/index.html.erb
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><%= link_to "Home", root_path %></li> 
    <li><span class="show-for-sr">Current: </span>View Cleanups</li>
  </ul>
</nav>

<h1>View Cleanups</h1>

<div>
    <h3>Use the links below to view cleanup records for a particular state or territory.</h3>
</div>

<div class="grid-container">
  <div class="grid-x grid-margin-x small-up-2 medium-up-3" data-equalizer data-equalize-on="medium" id="test-eq">
    <div class="cell">
      <div class="card" data-equalizer-watch>
        <div class="card-section">
        <strong><h4>New England:</h4></strong>  
        <ul>
            <li>
                <%= link_to 'Connecticut', "/states/CT" %>
            </li>
            <li>
                <%= link_to 'Maine', "/states/ME" %>
            </li>
            <li>
                <%= link_to 'Massachusetts', "/states/MA" %>
            </li>
            <li>
                <%= link_to 'New Hampshire', "/states/NH" %>
            </li>
            <li>
                <%= link_to 'Rhode Island', "/states/RI" %>
            </li>
            <li>
                <%= link_to 'Vermont', "/states/VT" %>
            </li>
        </ul>
        </div>
      </div>
    </div>
    <div class="cell">
      <div class="card" data-equalizer-watch>
        <div class="card-section">
        <strong><h4>Mid Atlantic:</h4></strong>
        <ul>
            <li>
                <%= link_to 'Delaware', "/states/DE" %>
            </li>
            <li>
                <%= link_to 'District of Columbia', "/states/DC" %>
            </li>
            <li>
                <%= link_to 'Maryland', "/states/MD" %>
            </li>
            <li>
                <%= link_to 'New Jersey', "/states/NJ" %>
            </li>
            <li>
                <%= link_to 'New York', "/states/NY" %>
            </li>
            <li>
                <%= link_to 'Pennsylvania', "/states/PA" %>
            </li>
        </ul>
        </div>
      </div>
    </div>
    <div class="cell">
      <div class="card" data-equalizer-watch>
        <div class="card-section">
        <strong><h4>South:</h4></strong>
        <ul>
            <li>
                <%= link_to 'Alabama', "/states/AL" %>
            </li>
            <li>
                <%= link_to 'Arkansas', "/states/AR" %>
            </li>
            <li>
                <%= link_to 'Florida', "/states/FL" %>
            </li>
            <li>
                <%= link_to 'Georgia', "/states/GA" %>
            </li>
            <li>
                <%= link_to 'Kentucky', "/states/KY" %>
            </li>
            <li>
                <%= link_to 'Louisiana', "/states/LA" %>
            </li>
            <li>
                <%= link_to 'Mississippi', "/states/MS" %>
            </li>
            <li>
                <%= link_to 'North Carolina', "/states/NC" %>
            </li>
            <li>
                <%= link_to 'Puerto Rico', "/states/PR" %>
            </li>
            <li>
                <%= link_to 'South Carolina', "/states/SC" %>
            </li>
            <li>
                <%= link_to 'Tennessee', "/states/TN" %>
            </li>
            <li>
                <%= link_to 'Virginia', "/states/VA" %>
            </li>
            <li>
                <%= link_to 'West Virginia', "/states/WV" %>
            </li>
        </ul>
        </div>
      </div>
    </div>
    <div class="cell">
      <div class="card" data-equalizer-watch>
        <div class="card-section">
        <strong><h4>Midwest:</h4></strong>
        <ul>
            <li>
                <%= link_to 'Illinois', "/states/IL" %>
            </li>
            <li>
                <%= link_to 'Indiana', "/states/IN" %>
            </li>
            <li>
                <%= link_to 'Iowa', "/states/IA" %>
            </li>
            <li>
                <%= link_to 'Kansas', "/states/KA" %>
            </li>
            <li>
                <%= link_to 'Michigan', "/states/MI" %>
            </li>
            <li>
                <%= link_to 'Minnesota', "/states/MN" %>
            </li>
            <li>
                <%= link_to 'Missouri', "/states/MO" %>
            </li>
            <li>
                <%= link_to 'Nebraska', "/states/NE" %>
            </li>
            <li>
                <%= link_to 'North Dakota', "/states/ND" %>
            </li>
            <li>
                <%= link_to 'Ohio', "/states/OH" %>
            </li>
            <li>
                <%= link_to 'South Dakota', "/states/SD" %>
            </li>
            <li>
                <%= link_to 'Wisconsin', "/states/WI" %>
            </li>
        </ul>
        </div>
      </div>
    </div>
    <div class="cell">
      <div class="card" data-equalizer-watch>
        <div class="card-section">
        <strong><h4>Southwest:</h4></strong>
        <ul>
            <li>
                <%= link_to 'Arizona', "/states/AZ" %>
            </li>
            <li>
                <%= link_to 'New Mexico', "/states/NM" %>
            </li>
            <li>
                <%= link_to 'Oklahoma', "/states/OK" %>
            </li>
            <li>
                <%= link_to 'Texas', "/states/TX" %>
            </li>
        </ul>
        </div>
      </div>
    </div>
    <div class="cell">
      <div class="card" data-equalizer-watch>
        <div class="card-section">
        <strong><h4>West:</h4></strong>
        <ul>
            <li>
                <%= link_to 'Alaska', "/states/AK" %>
            </li>
            <li>
                <%= link_to 'California', "/states/CA" %>
            </li>
            <li>
                <%= link_to 'Colorado', "/states/CO" %>
            </li>
            <li>
                <%= link_to 'Hawaii', "/states/HI" %>
            </li>
            <li>
                <%= link_to 'Idaho', "/states/ID" %>
            </li>
            <li>
                <%= link_to 'Montana', "/states/MT" %>
            </li>
            <li>
                <%= link_to 'Nevada', "/states/NV" %>
            </li>
            <li>
                <%= link_to 'Oregon', "/states/OR" %>
            </li>
            <li>
                <%= link_to 'Utah', "/states/UT" %>
            </li>
            <li>
                <%= link_to 'Washington', "/states/WA" %>
            </li>
            <li>
                <%= link_to 'Wyoming', "/states/WY" %>
            </li>
        </ul>
        </div>
      </div>
    </div>
  </div>
</div>


 

app/views/cleanups/new.html.erb
<div class="text-center">
<h1>Log A Cleanup</h1>
</div>

<div>
  <% if user_signed_in? %>
      <%= render 'cleanup_form' %>
  <% else %>
      <div class="text-center">
      <h3><%= 'Interested in logging a cleanup? Excellent! Please sign in, or sign up for a new account--it\'s free!' %></h3>
      </div>
      <div class="callout secondary cell small-12 medium-4">
      <h3>I'm a returning user... <%= link_to "Sign In", new_user_session_path %></h3>
      </div>
      <div class="callout secondary cell small-12 medium-4">
      <h3>I'm a new user... <%= link_to "Sign Up", new_user_registration_path %></h3>
      </div>
  <% end %>
</div>

app/views/cleanups/show.html.erb
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><%= link_to "Home", root_path %></li> 
    <li><%= link_to "View Cleanups", cleanups_path %></li>
    <li><%= link_to "State", state_path(@cleanup.state) %></li>
    <li><%= link_to "City", state_city_path(@cleanup.state, @cleanup.city) %></li>
    <li><span class="show-for-sr">Current: </span>Cleanup Log</li>
  </ul>
</nav>

<h1>Cleanup Log</h1>

<div class="callout secondary">
  <h5><%= @cleanup.title %></h5>
</div>

  <table class= "hover">
    <thead>
      <tr>
        <th width="125">Date</th>
        <th width="125">Posted By</th>
        <th width="125">City</th> 
        <th width="75">State</th> 
        <th width="100">Cleanup Type</th> 
        <th width="100">Total Volunteers</th> 
        <th width="100">Total Trash (lbs.)</th> 
        <th>Description</th>    
      </tr>
    </thead>
  <tbody>
    <tr>
      <td><%= @cleanup.date.strftime("%m-%d-%Y") %></td>
      <td><%= @cleanup.posted_by %></td>   
      <td><%= @cleanup.city %></td>
      <td><%= @cleanup.state %></td>
      <td><%= @cleanup.cleanup_type %></td>
      <td><%= @cleanup.volunteers %></td>
      <td><%= @cleanup.total_trash %></td>
      <td><%= @cleanup.description %></td>
    </tr>    
  </tbody>
</table>

<div class="grid-container">
<div class="grid-x grid-margin-x small-up-2 medium-up-4">
  <% if @cleanup.cleanup_photo? %>
    <div class="cell">
      <div class="card">
        <div class="card-section">
        <%= image_tag(@cleanup.cleanup_photo.thumb.url, alt: 'Image') if @cleanup.cleanup_photo? %>
        </div>
      </div>
    </div>
  <% end %>
</div>
</div>

<nav class="bottom-bar">
    <div class="bottom-bar-left">
      <ul class="menu">  
      <% if current_user == @cleanup.user %>
        <%= link_to 'My Cleanups', user_path %>
        <%= link_to 'Edit Cleanup', edit_cleanup_path %> 
      <% end %>
      </ul>
    </div>
</nav>

app/views/details/index.html.erb
<h1>About<%=image_tag("noun_Litter_872690.png", height: 95, width: 95)%></h1>

<h3>What is Cleanups?</h3>
    <p>Cleanups is an app that helps you keep track of individual or group efforts to clean litter from roadsides, neighborhoods, parks, waterways...anywhere!</p>
<h3>How can I log my cleanup on this site?</h3>
    <p>It&#39s easy! Sign up for a free account, click &#34Log A Cleanup&#34 and complete the cleanup form. The form will ask you to enter data about your cleanup, including the date, location, number of volunteers, and total trash collected (an estimate is fine). You can also add a short description of the event and some photos, if you like. When you&#39re ready, submit the form. That&#39s it! You can view and edit all of your logged cleanups from the &#34My Cleanups&#34 page.</p>
<h3>Can I view cleanups posted by others?</h3>
    <p>Yes! All cleanups logged on this site are publicly viewable. Curious to see cleanup activity in other states or in your own city? We encourage you to check out the &#34View Cleanups&#34 page, where you can find cleanup events organized by state and city.</p>
<h3>What other features can I find here?</h3>
    <p>Cleanups recently added a feature that calculates and displays the total trash collected at the state level--click on a state with at least one logged clenaup to see this feature in action! As the app evolves, we hope to add more features in the future, including more statistics and a member forum. We would love to see Cleanups provide an inspiring and encouraging space for people interested in finding ways to make a difference in their communities and in helping the environment.</p>

app/views/homes/index.html.erb
<div class="text-center">
  <h1>Tired of litter everywhere? Let's clean it up!</h1>
  <h2>Use <strong>Cleanups</strong> to log and keep track of your initiatives to remove trash from roadsides, parks, beaches, etc.</h2>
</div>
<hr>

<div class="callout secondary cell small-12 medium-4">
  <h3>I'd like to... <%= link_to "View Cleanups", cleanups_path %></h3>
</div>

<div class="callout secondary cell small-12 medium-4">
  <h3>I'd like to... <%= link_to "Log A Cleanup", new_cleanup_path %></h3>
</div>

<!-- images have no padding -->
<div class="grid-container">
  <div class="grid-x grid-margin-x small-up-2 medium-up-4">
    <div class="cell">
      <div class="card">
      <%=image_tag "noun_creek_22411.png" %>
      </div>
    </div>
    <div class="cell">
      <div class="card">
      <%=image_tag "noun_Road_936604.png" %>
      </div>
    </div>
    <div class="cell">
      <div class="card">
      <%=image_tag "noun_city building_849095.png" %>
      </div>
    </div>
    <div class="cell">
      <div class="card">
      <%=image_tag "noun_landscapes_1368885.png" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cleanups</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
  
<body> 
  
  <nav class="top-bar">
    <h1>
      <a href="/" style="color: #FEFEFE">Cleanups</a>
    </h1>
    <div class="top-bar-left">
      <ul class="menu">
        <%- if current_user -%>
          <%= link_to "My Cleanups", user_path(current_user), {:style=>'color:#FEFEFE;'} %>
        <%- end -%>  
        <%= link_to "View Cleanups", cleanups_path, {:style=>'color:#FEFEFE;'} %> 
        <%= link_to "Log A Cleanup", new_cleanup_path, {:style=>'color:#FEFEFE;'} %>
        <%= link_to "About", details_path, {:style=>'color:#FEFEFE;'} %>
      </ul>
    </div>

    <section class="top-bar-section">
      <ul class="right">
      <ul class="menu">
        <%- if current_user -%>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete, :style=>'color:#FEFEFE;' %></li>
          <li><%= link_to 'Edit Account', edit_user_registration_path, {:style=>'color:#FEFEFE;'} %></li>
          <li><%= link_to "Admin", admin_users_path, {:style=>'color:#FEFEFE;'} if current_user.is_admin? %><li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path, {:style=>'color:#FEFEFE;'} %></li>
          <li><%= link_to 'Sign In', new_user_session_path, {:style=>'color:#FEFEFE;'} %></li>
        <%- end -%>
      </ul>
      </ul>
    </section>
  </nav>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <%= value %>
    </div>
  <%- end -%>

  <div class="grid-container">
  <%= yield %>
  </div>

  <%= javascript_include_tag 'application' %>
  
  <%- if Rails.env.development? || Rails.env.test? -%> 
    <%= javascript_tag do %>
      window.railsEnv = '<%= Rails.env %>'
    <%- end -%>
  <%- end -%>
  <%= javascript_pack_tag 'application' %>
  
  <%= yield :extra_footer %>
</body>
</html>

app/views/states/show.html.erb
<nav aria-label="You are here:" role="navigation">
  <ul class="breadcrumbs">
    <li><%= link_to "Home", root_path %></li> 
    <li><%= link_to "View Cleanups", cleanups_path %></li>
    <li><span class="show-for-sr">Current: </span>State</li>
  </ul>
</nav>

  <div>
    <% if @state_trash >= 1 %>
      <div class="circle"><br />State Trash Total: <br /> <%= @state_trash %> lbs.</div>
  </div>
  <% end %>

<h1><%= "Cleanups By State/Territory: #{@state_name}" %></h1>
<h3>Locations where cleanups have been logged will be linked below.</h3>

<table class= "hover">
  <thead>
    <tr>
      <th>City</th>
    </tr>
  </thead>
  <tbody>
    <div>
      <% @cleanup_cities.each do |cleanup| %>
        <tr><td><%= link_to cleanup, state_city_path(params[:id], cleanup) %></td></tr>
      <% end %>
    </div>
  </tbody>
</table>

app/views/users/show.html.erb
<h1>My Cleanups</h1>

<table class= "hover">
  <thead>
    <tr>
      <th width="200">Date</th>
      <th>Cleanup Event</th>   
    </tr>
  </thead>

<tbody>

  <% @cleanups.each do |cleanup| %>
    <tr>
      <td><%= cleanup.date.strftime("%m-%d-%Y") %></td> 
      <td><%= link_to cleanup.title, cleanup %></td>
    </tr>   
    <% end %>
  </tbody>
</table>